theme: jekyll-theme-slate
title: Welcome to Pandelani Nekhumbe's homepage! Kha vha pfe vho tanganedzwa.
description: Feel free to bookmark this to keep an eye on my projects updates!
author: Pandelani Nekhumbe
# Includes an icon in the footer for each username you enter
